nelmio_cors:
  defaults:
    allow_origin: ["https://devwebcollin.fr"]
    allow_methods: ["GET", "POST", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    max_age: 3600
  paths:
    "^/api": null